---
name: Ubuntu

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: configure
        run: cmake -S test -B build -DENABLE_TEST_COVERAGE=1

      - name: build
        run: cmake --build build --config Debug -j4

      - name: test
        run: |
          cd build
          ctest --build-config Debug

      - name: install code coverage tools
        run: |
          wget https://github.com/linux-test-project/lcov/releases/download/v1.16/lcov-1.16.tar.gz
          tar xvfz lcov-1.16.tar.gz;
          sudo make install -C lcov-1.16

      - name: collect code coverage
        run: |
          lcov --gcov-tool $(which gcov) --directory . --capture --no-external --exclude "*tests*" --exclude "*_deps*" --quiet --output-file coverage.info
          lcov --gcov-tool $(which gcov) --list coverage.info
          bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
